version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=InimigosDaIgnorancia
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - spider_web
  crawler:
    build: web_crawler/
    restart: always
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    volumes: 
      - ./web_crawler:/web_crawler
    networks:
      - spider_web
  prolog:
    build: prolog/
    restart: always
    volumes: 
      - ./prolog:/prolog
    networks:
      - spider_web

networks:
  spider_web:

volumes:
  db:
